@startuml
Class Member{
                 {field} email: String
                 }
Class BoardMember{
                 }
Class Event{
           {field} date: Date
           {field} description: String
           {method} assign(l: Location): void
           }
Class Conference{
                {field} max_attendees: Integer
                }
Class BoardMeeting{
                  }
Class Location{
              {field} description: String
              {field} address: String
              }
Class Person{
            {field} name: String
            }
Class AAUOC{
           {method} newLocation(l: Location): void
           {method} newEvent(e: Event): void
           {method} newPerson(p: Person): void
           {method} informEvent(e: Event): void
           {method} register(m: Member, e: Event): void
           }

AAUOC o-- "0...*" Location
AAUOC o-- "0...*" Event
AAUOC o-- "0...*" Person

Event "0...*" - "1" Location : isLocated In

Event <|-- BoardMeeting
Event <|-- Conference

Person <|-- Member
Conference "0...*" - "0...*" Person : attendsTo

Member <|-- BoardMember
Member "0...*" - "0...*" Event : attendsTo

BoardMeeting "0...*" - "0...*" BoardMember

@enduml